CREATE TABLE `employer_settings` (
  `employer_id` integer PRIMARY KEY NOT NULL,
  `logo_url` text,
  `typical_pay_basis` text DEFAULT 'period' NOT NULL,
  `typical_annual_leave_days` real DEFAULT 28 NOT NULL,
  `typical_weekly_hours` real DEFAULT 37.5 NOT NULL,
  `minimum_hourly_rate` real DEFAULT 12.71 NOT NULL,
  `auto_works_number` integer DEFAULT true NOT NULL,
  `next_works_number` integer DEFAULT 1 NOT NULL,
  `withhold_tax_refund_zero_pay` integer DEFAULT false NOT NULL,
  `no_ssp_alternate_scheme` integer DEFAULT false NOT NULL,
  `opt_out_credit_checks` integer DEFAULT false NOT NULL,
  `preferred_credential_label` text,
  `primary_contact_name` text,
  `primary_contact_email` text,
  `primary_contact_phone` text,
  `alternate_contact_name` text,
  `alternate_contact_email` text,
  `managed_by` text,
  `client_status` text DEFAULT 'active' NOT NULL,
  `colour_reference` text DEFAULT '#087b79' NOT NULL,
  `final_fps_due` text,
  `eps_due` text,
  `p60_due` text,
  `p11d_due` text,
  `document_password_strategy` text DEFAULT 'employee-postcode' NOT NULL,
  `created_at` text DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
  `updated_at` text DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
  FOREIGN KEY (`employer_id`) REFERENCES `employers`(`id`)
);
