
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb/
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    links:
      - "api:api"
    volumes:
      - /var/www/.well-known/pki-validation:/var/www/.well-known/pki-validation
  api:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
        MONGO_URL: ${MONGO_URL}
        DB_NAME: ${DB_NAME}
    ports:
      - "${APP_PORT}:4000"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    volumes:
    - ./uploads:/usr/app/uploads
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile