import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const runtimeTimestamp = () => new Date().toISOString();
const timestamps = {
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP").$defaultFn(runtimeTimestamp),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP").$defaultFn(runtimeTimestamp).$onUpdateFn(runtimeTimestamp),
};

export const employers = sqliteTable("employers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  legalName: text("legal_name"),
  address: text("address"),
  postcode: text("postcode"),
  payeReference: text("paye_reference"),
  accountsOfficeReference: text("accounts_office_reference"),
  companyNumber: text("company_number"),
  cisUtr: text("cis_utr"),
  payFrequency: text("pay_frequency").notNull().default("monthly"),
  taxYear: text("tax_year").notNull().default("2026/27"),
  smallEmployersRelief: integer("small_employers_relief", { mode: "boolean" }).notNull().default(false),
  employmentAllowance: integer("employment_allowance", { mode: "boolean" }).notNull().default(false),
  apprenticeshipLevy: integer("apprenticeship_levy", { mode: "boolean" }).notNull().default(false),
  apprenticeshipLevyAllowance: real("apprenticeship_levy_allowance").notNull().default(15000),
  cisContractor: integer("cis_contractor", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const eposClientMappings = sqliteTable("epos_client_mappings", {
  clientId: text("client_id").primaryKey(),
  practiceId: text("practice_id").notNull(),
  employerId: integer("employer_id").notNull().unique().references(() => employers.id),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP").$defaultFn(runtimeTimestamp),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP").$defaultFn(runtimeTimestamp).$onUpdateFn(runtimeTimestamp),
});

export const departments = sqliteTable("departments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  name: text("name").notNull(),
  nominalCode: text("nominal_code"),
  costCentre: text("cost_centre"),
});

export const employerSettings = sqliteTable("employer_settings", {
  employerId: integer("employer_id").primaryKey().references(() => employers.id),
  logoUrl: text("logo_url"),
  typicalPayBasis: text("typical_pay_basis").notNull().default("period"),
  typicalAnnualLeaveDays: real("typical_annual_leave_days").notNull().default(28),
  typicalWeeklyHours: real("typical_weekly_hours").notNull().default(37.5),
  minimumHourlyRate: real("minimum_hourly_rate").notNull().default(12.71),
  autoWorksNumber: integer("auto_works_number", { mode: "boolean" }).notNull().default(true),
  nextWorksNumber: integer("next_works_number").notNull().default(1),
  firstPayDate: text("first_pay_date"),
  withholdTaxRefundZeroPay: integer("withhold_tax_refund_zero_pay", { mode: "boolean" }).notNull().default(false),
  noSspAlternateScheme: integer("no_ssp_alternate_scheme", { mode: "boolean" }).notNull().default(false),
  optOutCreditChecks: integer("opt_out_credit_checks", { mode: "boolean" }).notNull().default(false),
  preferredCredentialLabel: text("preferred_credential_label"),
  primaryContactName: text("primary_contact_name"),
  primaryContactEmail: text("primary_contact_email"),
  primaryContactPhone: text("primary_contact_phone"),
  alternateContactName: text("alternate_contact_name"),
  alternateContactEmail: text("alternate_contact_email"),
  bankName: text("bank_name"),
  bankAccountName: text("bank_account_name"),
  bankSortCode: text("bank_sort_code"),
  bankAccountNumber: text("bank_account_number"),
  employerNotes: text("employer_notes"),
  managedBy: text("managed_by"),
  clientStatus: text("client_status").notNull().default("active"),
  colourReference: text("colour_reference").notNull().default("#087b79"),
  finalFpsDue: text("final_fps_due"),
  epsDue: text("eps_due"),
  p60Due: text("p60_due"),
  p11dDue: text("p11d_due"),
  documentPasswordStrategy: text("document_password_strategy").notNull().default("employee-postcode"),
  reportAccentColour: text("report_accent_colour").notNull().default("#087b79"),
  reportHeaderText: text("report_header_text"),
  reportFooterText: text("report_footer_text"),
  reportStationeryMode: text("report_stationery_mode").notNull().default("standard"),
  payslipDesign: text("payslip_design"),
  accountingDefaultWagesCode: text("accounting_default_wages_code").notNull().default("WAGES"),
  accountingControlCode: text("accounting_control_code").notNull().default("CTRL"),
  accountingPayeCode: text("accounting_paye_code").notNull().default("TAX"),
  accountingNicCode: text("accounting_nic_code").notNull().default("NIC"),
  accountingPensionCode: text("accounting_pension_code").notNull().default("PENS"),
  accountingOtherDeductionsCode: text("accounting_other_deductions_code").notNull().default("OTHER"),
  accountingEmployerNicExpenseCode: text("accounting_employer_nic_expense_code").notNull().default("ERNIC"),
  accountingEmployerPensionExpenseCode: text("accounting_employer_pension_expense_code").notNull().default("ERPENS"),
  ...timestamps,
});

export const employerCalendarDays = sqliteTable("employer_calendar_days", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  taxYear: text("tax_year").notNull(),
  date: text("date").notNull(),
  name: text("name").notNull(),
  type: text("type").notNull().default("national-holiday"),
  status: text("status").notNull().default("active"),
  ...timestamps,
},table=>[uniqueIndex("employer_calendar_days_employer_date_type_unique").on(table.employerId,table.date,table.type)]);

export const adminUsers = sqliteTable("admin_users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  email: text("email").notNull().unique(),
  displayName: text("display_name").notNull(),
  passwordHash: text("password_hash").notNull(),
  status: text("status").notNull().default("active"),
  lastLoginAt: text("last_login_at"),
  ...timestamps,
});

export const employerMemberships = sqliteTable("employer_memberships", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  userId: integer("user_id").notNull().references(() => adminUsers.id),
  role: text("role").notNull().default("viewer"),
  canViewConfidential: integer("can_view_confidential", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const adminSessions = sqliteTable("admin_sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id").notNull().references(() => adminUsers.id),
  tokenHash: text("token_hash").notNull().unique(),
  expiresAt: text("expires_at").notNull(),
  revokedAt: text("revoked_at"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP").$defaultFn(runtimeTimestamp),
});

export const employees = sqliteTable("employees", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  departmentId: integer("department_id").references(() => departments.id),
  payrollId: text("payroll_id").notNull(),
  worksNumber: text("works_number"),
  title: text("title"),
  firstName: text("first_name").notNull(),
  middleNames: text("middle_names"),
  lastName: text("last_name").notNull(),
  dateOfBirth: text("date_of_birth"),
  gender: text("gender"),
  address: text("address"),
  postcode: text("postcode"),
  email: text("email"),
  phone: text("phone"),
  niNumber: text("ni_number"),
  nationality: text("nationality"),
  passportNumber: text("passport_number"),
  maritalStatus: text("marital_status"),
  jobTitle: text("job_title"),
  startDate: text("start_date"),
  leavingDate: text("leaving_date"),
  starterEvidence: text("starter_evidence"),
  starterDeclaration: text("starter_declaration"),
  p45LeavingDate: text("p45_leaving_date"),
  p45PreviousPay: real("p45_previous_pay").notNull().default(0),
  p45PreviousTax: real("p45_previous_tax").notNull().default(0),
  p45ReceivedAfterPayroll: integer("p45_received_after_payroll", { mode: "boolean" }).notNull().default(false),
  p60TaxYear: text("p60_tax_year"),
  p60ReferenceOnly: integer("p60_reference_only", { mode: "boolean" }).notNull().default(false),
  taxCode: text("tax_code").notNull().default("1257L"),
  week1Month1: integer("week1_month1", { mode: "boolean" }).notNull().default(false),
  niCategory: text("ni_category").notNull().default("A"),
  director: integer("director", { mode: "boolean" }).notNull().default(false),
  directorStart: text("director_start"),
  directorEnd: text("director_end"),
  alternativeDirectorNic: integer("alternative_director_nic", { mode: "boolean" }).notNull().default(false),
  noSecondaryNic: integer("no_secondary_nic", { mode: "boolean" }).notNull().default(false),
  studentLoanPlan: text("student_loan_plan"),
  postgraduateLoan: integer("postgraduate_loan", { mode: "boolean" }).notNull().default(false),
  payBasis: text("pay_basis").notNull().default("period"),
  annualSalary: real("annual_salary").notNull().default(0),
  hourlyRate: real("hourly_rate").notNull().default(0),
  dailyRate: real("daily_rate").notNull().default(0),
  workingDaysPerWeek: real("working_days_per_week").notNull().default(5),
  contractedHours: real("contracted_hours").notNull().default(0),
  minimumWageCategory: text("minimum_wage_category").notNull().default("age-based"),
  apprenticeshipStartDate: text("apprenticeship_start_date"),
  annualLeaveDays: real("annual_leave_days").notNull().default(28),
  paymentMethod: text("payment_method").notNull().default("credit-transfer"),
  bankName: text("bank_name"),
  accountName: text("account_name"),
  sortCode: text("sort_code"),
  accountNumber: text("account_number"),
  irregularPayment: integer("irregular_payment", { mode: "boolean" }).notNull().default(false),
  zeroPayFpsExclusion: integer("zero_pay_fps_exclusion", { mode: "boolean" }).notNull().default(false),
  reportedPayFrequency: text("reported_pay_frequency").notNull().default("monthly"),
  workplacePostcode: text("workplace_postcode"),
  previousPayrollId: text("previous_payroll_id"),
  paymentToBody: integer("payment_to_body", { mode: "boolean" }).notNull().default(false),
  trivialCommutation: integer("trivial_commutation", { mode: "boolean" }).notNull().default(false),
  flexibleDrawdown: integer("flexible_drawdown", { mode: "boolean" }).notNull().default(false),
  employeePortal: integer("employee_portal", { mode: "boolean" }).notNull().default(false),
  portalCanEditBank: integer("portal_can_edit_bank", { mode: "boolean" }).notNull().default(false),
  confidential: integer("confidential", { mode: "boolean" }).notNull().default(false),
  managerName: text("manager_name"),
  emergencyContactName: text("emergency_contact_name"),
  emergencyContactPhone: text("emergency_contact_phone"),
  emergencyContactRelationship: text("emergency_contact_relationship"),
  medicalInformation: text("medical_information"),
  hrNotes: text("hr_notes"),
  hrNotesConfidential: integer("hr_notes_confidential", { mode: "boolean" }).notNull().default(true),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const payPeriods = sqliteTable("pay_periods", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  taxYear: text("tax_year").notNull(),
  periodNumber: integer("period_number").notNull(),
  frequency: text("frequency").notNull().default("monthly"),
  periodStart: text("period_start"),
  periodEnd: text("period_end"),
  payDate: text("pay_date"),
  status: text("status").notNull().default("open"),
  finalisedAt: text("finalised_at"),
  ...timestamps,
},table=>[uniqueIndex("pay_periods_employer_tax_year_period_unique").on(table.employerId,table.taxYear,table.periodNumber)]);

export const payrollOpeningBalances = sqliteTable("payroll_opening_balances", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  taxYear: text("tax_year").notNull(),
  firstPayFlowPeriod: integer("first_payflow_period").notNull(),
  grossPay: real("gross_pay").notNull().default(0),
  taxablePay: real("taxable_pay").notNull().default(0),
  payeTax: real("paye_tax").notNull().default(0),
  nicablePay: real("nicable_pay").notNull().default(0),
  earningsAtLel: real("earnings_at_lel").notNull().default(0),
  earningsLelToPt: real("earnings_lel_to_pt").notNull().default(0),
  earningsPtToUel: real("earnings_pt_to_uel").notNull().default(0),
  earningsAboveUel: real("earnings_above_uel").notNull().default(0),
  employeeNic: real("employee_nic").notNull().default(0),
  employerNic: real("employer_nic").notNull().default(0),
  nicCategoryBreakdown: text("nic_category_breakdown").notNull().default("[]"),
  studentLoan: real("student_loan").notNull().default(0),
  postgraduateLoan: real("postgraduate_loan").notNull().default(0),
  statutoryPay: real("statutory_pay").notNull().default(0),
  employeePension: real("employee_pension").notNull().default(0),
  employerPension: real("employer_pension").notNull().default(0),
  netPay: real("net_pay").notNull().default(0),
  source: text("source").notNull().default("prior-payroll-p11"),
  notes: text("notes"),
  payloadChecksum: text("payload_checksum").notNull(),
  ...timestamps,
},table=>[uniqueIndex("payroll_opening_balances_employer_employee_year_unique").on(table.employerId,table.employeeId,table.taxYear)]);

export const payRuns = sqliteTable("pay_runs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  payPeriodId: integer("pay_period_id").notNull().references(() => payPeriods.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  grossPay: real("gross_pay").notNull().default(0),
  taxablePay: real("taxable_pay").notNull().default(0),
  nicablePay: real("nicable_pay").notNull().default(0),
  payeTax: real("paye_tax").notNull().default(0),
  employeeNic: real("employee_nic").notNull().default(0),
  employerNic: real("employer_nic").notNull().default(0),
  studentLoan: real("student_loan").notNull().default(0),
  postgraduateLoan: real("postgraduate_loan").notNull().default(0),
  pensionSchemeId: integer("pension_scheme_id"),
  pensionablePay:real("pensionable_pay").notNull().default(0),
  employeePension: real("employee_pension").notNull().default(0),
  employerPension: real("employer_pension").notNull().default(0),
  statutoryPay: real("statutory_pay").notNull().default(0),
  otherDeductions: real("other_deductions").notNull().default(0),
  netPay: real("net_pay").notNull().default(0),
  payrollNote: text("payroll_note"),
  rtiSnapshot: text("rti_snapshot"),
  pensionSnapshot: text("pension_snapshot"),
  status: text("status").notNull().default("draft"),
  ...timestamps,
});

export const recurringPayItems = sqliteTable("recurring_pay_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  taxYear: text("tax_year").notNull().default("2026/27"),
  type: text("type").notNull(),
  name: text("name").notNull(),
  amount: real("amount").notNull().default(0),
  taxable: integer("taxable", { mode: "boolean" }).notNull().default(true),
  nicable: integer("nicable", { mode: "boolean" }).notNull().default(true),
  pensionable: integer("pensionable", { mode: "boolean" }).notNull().default(true),
  startPeriod: integer("start_period").notNull(),
  endPeriod: integer("end_period").notNull(),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const payrollAdjustments = sqliteTable("payroll_adjustments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  payPeriodId: integer("pay_period_id").notNull().references(() => payPeriods.id),
  type: text("type").notNull(),
  amount: real("amount").notNull(),
  reason: text("reason").notNull(),
  status: text("status").notNull().default("active"),
  createdBy: text("created_by").notNull(),
  reversedAt: text("reversed_at"),
  ...timestamps,
});

export const payItems = sqliteTable("pay_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  payRunId: integer("pay_run_id").notNull().references(() => payRuns.id),
  type: text("type").notNull(),
  name: text("name").notNull(),
  quantity: real("quantity").notNull().default(1),
  rate: real("rate").notNull().default(0),
  amount: real("amount").notNull().default(0),
  taxable: integer("taxable", { mode: "boolean" }).notNull().default(true),
  nicable: integer("nicable", { mode: "boolean" }).notNull().default(true),
  pensionable: integer("pensionable", { mode: "boolean" }).notNull().default(true),
  recurringItemId: integer("recurring_item_id").references(() => recurringPayItems.id),
});

export const leaveEvents = sqliteTable("leave_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  type: text("type").notNull(),
  subtype: text("subtype"),
  startDate: text("start_date").notNull(),
  endDate: text("end_date").notNull(),
  qualifyingDays: integer("qualifying_days").notNull().default(0),
  qualifyingDaysPerWeek: integer("qualifying_days_per_week").notNull().default(7),
  qualifyingWeekdays: text("qualifying_weekdays").notNull().default("1,2,3,4,5,6,7"),
  excludedCalendarDates: text("excluded_calendar_dates").notNull().default("[]"),
  averageWeeklyEarnings: real("average_weekly_earnings").notNull().default(0),
  averageWeeklyEarningsSource: text("average_weekly_earnings_source").notNull().default("manual"),
  relevantPeriodStart: text("relevant_period_start"),
  relevantPeriodEnd: text("relevant_period_end"),
  relevantPayTotal: real("relevant_pay_total").notNull().default(0),
  statutoryAmount: real("statutory_amount").notNull().default(0),
    recoveredAmount: real("recovered_amount").notNull().default(0),
    childBirthDate: text("child_birth_date"),
    neonatalCareStartDate: text("neonatal_care_start_date"),
    neonatalCareEndDate: text("neonatal_care_end_date"),
    neonatalTier: text("neonatal_tier"),
    relationshipDeclaration: integer("relationship_declaration", { mode: "boolean" }).notNull().default(false),
    caringResponsibilityDeclaration: integer("caring_responsibility_declaration", { mode: "boolean" }).notNull().default(false),
    familyEventReference: text("family_event_reference"),
    familyEventDate: text("family_event_date"),
    familyEventKind: text("family_event_kind"),
    sharedPayWeeksAvailable: integer("shared_pay_weeks_available"),
    statutoryPayPeriodStart: text("statutory_pay_period_start"),
    statutoryTouchDays: text("statutory_touch_days"),
    statutoryWorkedWeeks: text("statutory_worked_weeks"),
    statutoryPaidDayOffset: integer("statutory_paid_day_offset").notNull().default(0),
    notes: text("notes"),
  status: text("status").notNull().default("calculated"),
  ...timestamps,
});

export const statutoryNotices = sqliteTable("statutory_notices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  leaveEventId: integer("leave_event_id").references(() => leaveEvents.id),
  formType: text("form_type").notNull(),
  statutoryType: text("statutory_type").notNull(),
  decisionDate: text("decision_date").notNull(),
  payStartDate: text("pay_start_date").notNull(),
  payEndDate: text("pay_end_date"),
  reasonCode: text("reason_code").notNull(),
  reason: text("reason").notNull(),
  averageWeeklyEarnings: real("average_weekly_earnings").notNull().default(0),
  continuousEmploymentWeeks: integer("continuous_employment_weeks").notNull().default(0),
  evidenceReceived: integer("evidence_received", { mode: "boolean" }).notNull().default(false),
  noticeReceived: integer("notice_received", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull().default("issued"),
  issuedAt: text("issued_at"),
  employeeSnapshot: text("employee_snapshot"),
  payloadChecksum: text("payload_checksum"),
  cancellationReason: text("cancellation_reason"),
  ...timestamps,
});

export const hmrcNotices = sqliteTable("hmrc_notices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").references(() => employees.id),
  type: text("type").notNull(),
  noticeIdentifier: text("notice_identifier").notNull(),
  taxYear: text("tax_year").notNull(),
  issuedDate: text("issued_date").notNull(),
  effectiveDate: text("effective_date").notNull(),
  taxCode: text("tax_code"),
  week1Month1: integer("week1_month1", { mode: "boolean" }).notNull().default(false),
  loanAction: text("loan_action"),
  studentLoanPlan: text("student_loan_plan"),
  postgraduateLoan: integer("postgraduate_loan", { mode: "boolean" }).notNull().default(false),
  niNumber: text("ni_number"),
  message: text("message"),
  source: text("source").notNull().default("manual"),
  status: text("status").notNull().default("new"),
  appliedAt: text("applied_at"),
  ignoredAt: text("ignored_at"),
  payload: text("payload"),
  ...timestamps,
});

export const hmrcPayments = sqliteTable("hmrc_payments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  taxYear: text("tax_year").notNull(),
  taxMonth: integer("tax_month").notNull(),
  paymentDate: text("payment_date").notNull(),
  kind: text("kind").notNull().default("payment"),
  category: text("category"),
  amount: real("amount").notNull(),
  reference: text("reference").notNull(),
  method: text("method").notNull().default("bank-transfer"),
  notes: text("notes"),
  status: text("status").notNull().default("recorded"),
  voidedAt: text("voided_at"),
  voidReason: text("void_reason"),
  ...timestamps,
});

export const pensionSchemes = sqliteTable("pension_schemes", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  provider: text("provider").notNull(),
  schemeName: text("scheme_name").notNull(),
  employerReference: text("employer_reference"),
  employeeRate: real("employee_rate").notNull().default(5),
  employerRate: real("employer_rate").notNull().default(3),
  earningsBasis: text("earnings_basis").notNull().default("qualifying"),
  taxRelief: text("tax_relief").notNull().default("relief-at-source"),
  automaticEnrolmentScheme: integer("automatic_enrolment_scheme", { mode: "boolean" }).notNull().default(true),
  certificationDate: text("certification_date"),
  dutiesStartDate: text("duties_start_date"),
  nextReenrolmentDate: text("next_reenrolment_date"),
  declarationDueDate: text("declaration_due_date"),
  declarationStatus: text("declaration_status").notNull().default("not-filed"),
  contributionDueDay: integer("contribution_due_day").notNull().default(22),
  status: text("status").notNull().default("active"),
});

export const pensionMemberships = sqliteTable("pension_memberships", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  schemeId: integer("scheme_id").notNull().references(() => pensionSchemes.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  assessmentStatus: text("assessment_status").notNull().default("eligible"),
  membershipStatus: text("membership_status").notNull().default("active"),
  enrolmentDate: text("enrolment_date"),
  postponementEnd: text("postponement_end"),
  postponementNoticeDate: text("postponement_notice_date"),
  optOutDate: text("opt_out_date"),
  enrolmentInformationDate: text("enrolment_information_date"),
  optOutNoticeDate: text("opt_out_notice_date"),
  optOutNoticeValid: integer("opt_out_notice_valid", { mode: "boolean" }).notNull().default(false),
  ceasedDate: text("ceased_date"),
  lastReenrolmentDate: text("last_reenrolment_date"),
  employeeRefundDue:real("employee_refund_due").notNull().default(0),
  employerRefundDue:real("employer_refund_due").notNull().default(0),
  employerContributionRequired: integer("employer_contribution_required", { mode: "boolean" }).notNull().default(true),
  communicationDueDate: text("communication_due_date"),
  lastCommunicationDate: text("last_communication_date"),
  ...timestamps,
});

export const pensionMembershipEvents = sqliteTable("pension_membership_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  membershipId: integer("membership_id").notNull().references(() => pensionMemberships.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  schemeId: integer("scheme_id").notNull().references(() => pensionSchemes.id),
  eventType: text("event_type").notNull(),
  effectiveDate: text("effective_date").notNull(),
  previousStatus: text("previous_status"),
  newStatus: text("new_status").notNull(),
  details: text("details"),
  createdBy: text("created_by").notNull().default("Payroll administrator"),
  ...timestamps,
});

export const subcontractors = sqliteTable("subcontractors", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  name: text("name").notNull(),
  tradingName: text("trading_name"),
  type: text("type").notNull().default("sole-trader"),
  utr: text("utr"),
  companyNumber: text("company_number"),
  niNumber: text("ni_number"),
  partnerUtr: text("partner_utr"),
  address: text("address"),
  postcode: text("postcode"),
  email: text("email"),
  phone: text("phone"),
  verificationNumber: text("verification_number"),
  verificationMethod: text("verification_method"),
  verificationResponse: text("verification_response"),
  deductionRate: real("deduction_rate").notNull().default(20),
  verifiedAt: text("verified_at"),
  bankDetails: text("bank_details"),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const cisPayments = sqliteTable("cis_payments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  subcontractorId: integer("subcontractor_id").notNull().references(() => subcontractors.id),
  taxYear: text("tax_year").notNull().default("2026/27"),
  taxMonth: integer("tax_month").notNull(),
  paymentDate: text("payment_date").notNull(),
  invoiceNumber: text("invoice_number"),
  paymentRecipient: text("payment_recipient"),
  materialsEvidence: text("materials_evidence"),
  subcontractorName: text("subcontractor_name"),
  subcontractorType: text("subcontractor_type"),
  subcontractorUtr: text("subcontractor_utr"),
  subcontractorNiNumber: text("subcontractor_ni_number"),
  subcontractorCompanyNumber: text("subcontractor_company_number"),
  subcontractorPartnerUtr: text("subcontractor_partner_utr"),
  deductionRate: real("deduction_rate").notNull().default(30),
  verificationNumber: text("verification_number"),
  verificationMethod: text("verification_method"),
  verifiedAt: text("verified_at"),
  labour: real("labour").notNull().default(0),
  materials: real("materials").notNull().default(0),
  vat: real("vat").notNull().default(0),
  retention: real("retention").notNull().default(0),
  deduction: real("deduction").notNull().default(0),
  netPayment: real("net_payment").notNull().default(0),
  replacesPaymentId: integer("replaces_payment_id"),
  voidReason: text("void_reason"),
  status: text("status").notNull().default("draft"),
  ...timestamps,
});

export const submissions = sqliteTable("submissions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  payPeriodId: integer("pay_period_id").references(() => payPeriods.id),
  type: text("type").notNull(),
  dueDate: text("due_date"),
  payload: text("payload"),
  correlationId: text("correlation_id"),
  irMark: text("ir_mark"),
  status: text("status").notNull().default("draft"),
  preparedAt: text("prepared_at"),
  declarationAcceptedAt: text("declaration_accepted_at"),
  declarationAcceptedBy: text("declaration_accepted_by"),
  payloadChecksum: text("payload_checksum"),
  submittedAt: text("submitted_at"),
  response: text("response"),
  ...timestamps,
});

export const agentProfiles = sqliteTable("agent_profiles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  firmName: text("firm_name").notNull(),
  contactName: text("contact_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  address: text("address"),
  postcode: text("postcode"),
  agentReference: text("agent_reference"),
  vatRegistrationNumber: text("vat_registration_number"),
  defaultVatRate: real("default_vat_rate").notNull().default(20),
  paymentTermsDays: integer("payment_terms_days").notNull().default(14),
  invoicePrefix: text("invoice_prefix").notNull().default("PAY"),
  nextInvoiceNumber: integer("next_invoice_number").notNull().default(1),
  bankPaymentDetails: text("bank_payment_details"),
  payslipFooter: text("payslip_footer"),
  status: text("status").notNull().default("active"),
  ...timestamps,
},table=>[uniqueIndex("agent_profiles_employer_unique").on(table.employerId)]);

export const agentCharges = sqliteTable("agent_charges", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  chargeCode: text("charge_code").notNull(),
  description: text("description").notNull(),
  billingBasis: text("billing_basis").notNull().default("fixed"),
  unitRate: real("unit_rate").notNull().default(0),
  vatRate: real("vat_rate").notNull().default(20),
  effectiveFrom: text("effective_from"),
  effectiveTo: text("effective_to"),
  status: text("status").notNull().default("active"),
  ...timestamps,
},table=>[uniqueIndex("agent_charges_employer_code_unique").on(table.employerId,table.chargeCode)]);

export const agentInvoices = sqliteTable("agent_invoices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  invoiceNumber: text("invoice_number").notNull(),
  invoiceDate: text("invoice_date").notNull(),
  periodStart: text("period_start").notNull(),
  periodEnd: text("period_end").notNull(),
  dueDate: text("due_date").notNull(),
  status: text("status").notNull().default("draft"),
  payslipCount: integer("payslip_count").notNull().default(0),
  payrollPeriodCount: integer("payroll_period_count").notNull().default(0),
  employeeCount: integer("employee_count").notNull().default(0),
  submissionCount: integer("submission_count").notNull().default(0),
  netAmount: real("net_amount").notNull().default(0),
  vatAmount: real("vat_amount").notNull().default(0),
  grossAmount: real("gross_amount").notNull().default(0),
  lineItems: text("line_items").notNull().default("[]"),
  sourceEvidence: text("source_evidence").notNull().default("{}"),
  sourceChecksum: text("source_checksum").notNull(),
  issuedAt: text("issued_at"),
  voidedAt: text("voided_at"),
  voidReason: text("void_reason"),
  ...timestamps,
},table=>[uniqueIndex("agent_invoices_employer_number_unique").on(table.employerId,table.invoiceNumber)]);

export const expensesBenefits = sqliteTable("expenses_benefits", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  taxYear: text("tax_year").notNull(),
  category: text("category").notNull(),
  p11dSection: text("p11d_section"),
  nicTreatment: text("nic_treatment").notNull().default("class-1a"),
  providedDate: text("provided_date"),
  description: text("description"),
  cashEquivalent: real("cash_equivalent").notNull().default(0),
  payrolled: integer("payrolled", { mode: "boolean" }).notNull().default(false),
  class1aNic: real("class_1a_nic").notNull().default(0),
  benefitEvent: text("benefit_event"),
  availableFrom: text("available_from"),
  availableTo: text("available_to"),
  vehicleRegistration: text("vehicle_registration"),
  makeModel: text("make_model"),
  fuelType: text("fuel_type"),
  firstRegistered: text("first_registered"),
  co2Emissions: integer("co2_emissions"),
  zeroEmissionMileage: integer("zero_emission_mileage"),
  listPrice: real("list_price"),
  capitalContributions: real("capital_contributions"),
  privateUseContribution: real("private_use_contribution"),
  vanUseType: text("van_use_type"),
  vanFuelProvided: integer("van_fuel_provided", { mode: "boolean" }),
  vanFuelRepaid: integer("van_fuel_repaid", { mode: "boolean" }),
  vanSharedEmployees: integer("van_shared_employees"),
  loanOpeningBalance: real("loan_opening_balance"),
  loanClosingBalance: real("loan_closing_balance"),
  loanMaximumAggregateBalance: real("loan_maximum_aggregate_balance"),
  loanWholeMonths: integer("loan_whole_months"),
  loanInterestPaid: real("loan_interest_paid"),
  loanSalaryForegone: real("loan_salary_foregone"),
  accommodationAnnualValue: real("accommodation_annual_value"),
  accommodationProviderRent: real("accommodation_provider_rent"),
  accommodationPropertyCost: real("accommodation_property_cost"),
  accommodationImprovements: real("accommodation_improvements"),
  accommodationEmployeeCapital: real("accommodation_employee_capital"),
  accommodationEmployeeRent: real("accommodation_employee_rent"),
  accommodationAvailableDays: integer("accommodation_available_days"),
  accommodationSharedEmployees: integer("accommodation_shared_employees"),
  accommodationSalaryForegone: real("accommodation_salary_foregone"),
  status: text("status").notNull().default("draft"),
  voidReason: text("void_reason"),
  voidedAt: text("voided_at"),
  replacesBenefitId: integer("replaces_benefit_id"),
  copiedFromBenefitId: integer("copied_from_benefit_id"),
  copiedAt: text("copied_at"),
  ...timestamps,
},table=>[uniqueIndex("expenses_benefits_copied_source_unique").on(table.copiedFromBenefitId)]);

export const attachmentOrders = sqliteTable("attachment_orders", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  type: text("type").notNull(),
  issuingAuthority: text("issuing_authority"),
  reference: text("reference"),
  protectedEarnings: real("protected_earnings").notNull().default(0),
  deductionType: text("deduction_type").notNull().default("fixed"),
  deductionValue: real("deduction_value").notNull().default(0),
  calculationRule: text("calculation_rule").notNull().default("manual"),
  payFrequency: text("pay_frequency").notNull().default("monthly"),
  priority: integer("priority").notNull().default(50),
  arrears: real("arrears").notNull().default(0),
  effectiveDate: text("effective_date"),
    adminFee: real("admin_fee").notNull().default(1),
    balance: real("balance"),
    ordinaryDebtBalance: real("ordinary_debt_balance"),
    maintenanceDailyRate: real("maintenance_daily_rate").notNull().default(0),
  status: text("status").notNull().default("active"),
  ...timestamps,
});

export const attachmentOrderDeductions = sqliteTable("attachment_order_deductions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  attachmentOrderId: integer("attachment_order_id").notNull().references(() => attachmentOrders.id),
  payRunId: integer("pay_run_id").notNull().references(() => payRuns.id),
  deduction: real("deduction").notNull().default(0),
  adminFee: real("admin_fee").notNull().default(0),
  balanceAfter: real("balance_after"),
  rate: real("rate"),
  attachableNetPay: real("attachable_net_pay").notNull().default(0),
  protectedEarningsApplied: real("protected_earnings_applied").notNull().default(0),
  shortfall: real("shortfall").notNull().default(0),
  arrearsBefore: real("arrears_before").notNull().default(0),
    arrearsAfter: real("arrears_after").notNull().default(0),
    ordinaryDeduction: real("ordinary_deduction").notNull().default(0),
    maintenanceDeduction: real("maintenance_deduction").notNull().default(0),
    ordinaryBalanceAfter: real("ordinary_balance_after"),
  ...timestamps,
});

export const employeeLoans = sqliteTable("employee_loans", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  type: text("type").notNull(),
  reference: text("reference").notNull(),
  originalAmount: real("original_amount").notNull(),
  balance: real("balance").notNull(),
  regularDeduction: real("regular_deduction").notNull(),
  startDate: text("start_date").notNull(),
  status: text("status").notNull().default("active"),
  ...timestamps,
},table=>[uniqueIndex("employee_loans_employer_reference_unique").on(table.employerId,table.reference)]);

export const employeeLoanDeductions = sqliteTable("employee_loan_deductions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeeLoanId: integer("employee_loan_id").notNull().references(() => employeeLoans.id),
  payRunId: integer("pay_run_id").notNull().references(() => payRuns.id),
  amount: real("amount").notNull(),
  balanceBefore: real("balance_before").notNull(),
  balanceAfter: real("balance_after").notNull(),
  ...timestamps,
},table=>[uniqueIndex("employee_loan_deductions_loan_run_unique").on(table.employeeLoanId,table.payRunId)]);

export const employeePayRounding = sqliteTable("employee_pay_rounding", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  unit: real("unit").notNull().default(1),
  carry: real("carry").notNull().default(0),
  status: text("status").notNull().default("active"),
  ...timestamps,
},table=>[uniqueIndex("employee_pay_rounding_employer_employee_unique").on(table.employerId,table.employeeId)]);

export const payRoundingEntries = sqliteTable("pay_rounding_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeePayRoundingId: integer("employee_pay_rounding_id").notNull().references(() => employeePayRounding.id),
  payRunId: integer("pay_run_id").notNull().references(() => payRuns.id),
  unroundedNet: real("unrounded_net").notNull(),
  openingCarry: real("opening_carry").notNull(),
  roundedNet: real("rounded_net").notNull(),
  closingCarry: real("closing_carry").notNull(),
  adjustment: real("adjustment").notNull(),
  ...timestamps,
},table=>[uniqueIndex("pay_rounding_entries_setting_run_unique").on(table.employeePayRoundingId,table.payRunId)]);

export const holidayFundSettings = sqliteTable("holiday_fund_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  schemeType: text("scheme_type").notNull(),
  workerType: text("worker_type").notNull(),
  accrualRate: real("accrual_rate").notNull().default(0),
  openingBalance: real("opening_balance").notNull().default(0),
  currentBalance: real("current_balance").notNull().default(0),
  contractConfirmed: integer("contract_confirmed", { mode: "boolean" }).notNull().default(false),
  startDate: text("start_date").notNull(),
  status: text("status").notNull().default("active"),
  ...timestamps,
},table=>[uniqueIndex("holiday_fund_settings_employer_employee_unique").on(table.employerId,table.employeeId)]);

export const holidayFundEntries = sqliteTable("holiday_fund_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  holidayFundSettingId: integer("holiday_fund_setting_id").notNull().references(() => holidayFundSettings.id),
  payRunId: integer("pay_run_id").references(() => payRuns.id),
  payPeriodId: integer("pay_period_id").notNull().references(() => payPeriods.id),
  taxYear: text("tax_year").notNull(),
  periodNumber: integer("period_number").notNull(),
  schemeType: text("scheme_type").notNull(),
  workerType: text("worker_type").notNull(),
  contractConfirmed: integer("contract_confirmed", { mode: "boolean" }).notNull().default(false),
  accrualRate: real("accrual_rate").notNull().default(0),
  manualAdded: real("manual_added").notNull().default(0),
  requestedPaid: real("requested_paid").notNull().default(0),
  referencePayOverride: real("reference_pay_override"),
  accrualBase: real("accrual_base").notNull().default(0),
  addedAmount: real("added_amount").notNull().default(0),
  paidAmount: real("paid_amount").notNull().default(0),
  balanceBefore: real("balance_before").notNull().default(0),
  balanceAfter: real("balance_after").notNull().default(0),
  taxablePay: real("taxable_pay").notNull().default(0),
  nicablePay: real("nicable_pay").notNull().default(0),
  postTaxDeduction: real("post_tax_deduction").notNull().default(0),
  sourceChecksum: text("source_checksum"),
  status: text("status").notNull().default("draft"),
  ...timestamps,
},table=>[
  uniqueIndex("holiday_fund_entries_setting_period_unique").on(table.holidayFundSettingId,table.payPeriodId),
  uniqueIndex("holiday_fund_entries_setting_run_unique").on(table.holidayFundSettingId,table.payRunId),
  index("holiday_fund_entries_employer_period_idx").on(table.employerId,table.taxYear,table.periodNumber),
]);

export const employeePortalInvites = sqliteTable("employee_portal_invites", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  codeHash: text("code_hash").notNull(),
  expiresAt: text("expires_at").notNull(),
  usedAt: text("used_at"),
  ...timestamps,
});

export const employeePortalSessions = sqliteTable("employee_portal_sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  tokenHash: text("token_hash").notNull(),
  expiresAt: text("expires_at").notNull(),
  revokedAt: text("revoked_at"),
  ...timestamps,
});

export const employeeChangeRequests = sqliteTable("employee_change_requests", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  employeeId: integer("employee_id").notNull().references(() => employees.id),
  requestType: text("request_type").notNull(),
  proposedChanges: text("proposed_changes").notNull(),
  previousValues: text("previous_values").notNull(),
  status: text("status").notNull().default("pending"),
  employeeNote: text("employee_note"),
  reviewedBy: integer("reviewed_by").references(() => adminUsers.id),
  reviewedAt: text("reviewed_at"),
  reviewNote: text("review_note"),
  ...timestamps,
});

export const payrollVersions = sqliteTable("payroll_versions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").notNull().references(() => employers.id),
  label: text("label").notNull(),
  notes: text("notes"),
  backupPayload: text("backup_payload").notNull(),
  backupChecksum: text("backup_checksum").notNull(),
  schemaVersion: integer("schema_version").notNull(),
  recordCount: integer("record_count").notNull(),
  employeeCount: integer("employee_count").notNull(),
  payPeriodCount: integer("pay_period_count").notNull(),
  finalisedPeriodCount: integer("finalised_period_count").notNull(),
  createdBy: text("created_by").notNull(),
  restoredAt: text("restored_at"),
  restoredBy: text("restored_by"),
  status: text("status").notNull().default("active"),
  ...timestamps,
},table=>[
  index("payroll_versions_employer_created_idx").on(table.employerId,table.createdAt),
  uniqueIndex("payroll_versions_employer_checksum_unique").on(table.employerId,table.backupChecksum),
]);

export const auditLog = sqliteTable("audit_log", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  employerId: integer("employer_id").references(() => employers.id),
  actor: text("actor").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id"),
  before: text("before"),
  after: text("after"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP").$defaultFn(runtimeTimestamp),
});
